# Generated by Django 5.2.2 on 2025-06-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrasenia', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPER', 'Operador')], max_length=5)),
            ],
        ),
    ]
