# Generated by Django 5.2.2 on 2025-06-08 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_buque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('buque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sistema.buque')),
                ('estado', models.CharField(max_length=25)),
                ('operador', models.ForeignKey(limit_choices_to={'rol': 'operador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.empleado')),
            ],
        ),
    ]
