# Generated by Django 5.2.2 on 2025-06-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('PRO', 'Provisiones'), ('REP', 'Repuestos'), ('LIM', 'Limpieza y Aseo'), ('SEG', 'Seguridad'), ('SUM', 'Suministros Generales')], max_length=3)),
                ('cantidad', models.IntegerField()),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos/')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='sistema.inventario')),
            ],
        ),
    ]
