# Generated by Django 5.2.2 on 2025-06-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], max_length=15),
        ),
    ]
