# Generated by Django 5.2.2 on 2025-06-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_empleado_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='empleado',
        ),
    ]
