# Generated by Django 5.2.2 on 2025-06-11 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_servicio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='buque_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'inventario__operador__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.buque'),
        ),
    ]
